import React from 'react';
import NewsElement from './NewsElement';
import './News.css';


function News(){

    
        // var url = "https://newsapi.org/v2/everything?q=technology&from=2023-04-02&apiKey=72e136201f794007a9a03076a58686ba"
        
        // console.log(data);
        
        // var parsedData;

        const [articles, setArticles] = React.useState([]);
        React.useEffect(()=>{
            async function fetchData(){
                var url = "https://newsapi.org/v2/everything?q=technology&from=2023-04-06&apiKey=72e136201f794007a9a03076a58686ba"
                const data = await fetch(url);
                var parsedData = await data.json();
                console.log(parsedData);
                setArticles(parsedData.articles);
            }
            fetchData();
        },[]);

        function createNews(news){
            return(
                <NewsElement key ={news.url} source={news.url} imgSource={news.urlToImage?news.urlToImage:"https://p4.wallpaperbetter.com/wallpaper/912/429/111/technology-anonymous-hacker-hd-wallpaper-preview.jpg"} heading={news.title?news.title:""} author={news.author?news.author:""} desc={news.description?news.description:""}></NewsElement>
            )
        }
        // apiKey= "46a0da0c51a76484066f45db62020fbf"
    return(
        <div className='newsSection'>
            {articles.map(createNews)}
        </div>
    )
}

export default News;



// <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/31d877e439a4c8c09f555f4ecdab393e.jpg" heading="ChatGPT and Dall-E Should Watermark Their Results" author="Hany Farid" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
//             <NewsElement source="https://techcrunch.com/2023/03/27/france-bans-recreational-apps-like-tiktok-on-government-devices/" imgSource="https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?resize=1200,800" heading="France bans recreational apps like TikTok on government devices" author="Tech Crunch" desc="Shortly after rumors leaked of former President Donald Trump’s impending indictment, images purporting to show his arrest appeared online. These images looked like news photos, but they were fake. They were created by a generative artificial intelligence syst…"></NewsElement>
            